nginx:
    image: 'nginx'
    container_name: liveinginx-production
    restart: always
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public:/usr/share/nginx/html
        - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
        - /root/letsencrypt/live/livei.com/fullchain.pem:/etc/letsencrypt/live/livei.com/fullchain.pem
        - /root/letsencrypt/live/livei.com/privkey.pem:/etc/letsencrypt/live/livei.com/privkey.pem
    links:
        - php
php:
    image: 'php-fpm'
    container_name: liveiphp-production
    restart: always
    volumes:
        - ./public:/usr/share/nginx/html

mysql:
    image: 'mariadb'
    container_name: liveimysql-production
    restart: always
    ports:
        - '3306:3306'
    volumes:
        - ./database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: PLDTHOMEFIBR17e90
phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: liveiphpmyadmin-production
    restart: always
    links:
        - mysql:mysql
    ports:
        - 81:80
    environment:
        PMA_HOSTS: mysql
