<?php 

$DATABASE_HOST = '172.17.0.2';
$DATABASE_USER = 'root';
$DATABASE_PASS = 'PLDTHOMEFIBR17e90';
$DATABASE_NAME = 'liveidb';

$dbcon = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME);
$dbconn = new mysqli($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME);
?>